# docker compose file for running the sapphire forecast tools
# build: ieasyhydroforecast_data_root_dir=<path> docker-compose -f /path/to/docker-compose.yml build --no-cache
# run: ieasyhydroforecast_data_root_dir=<path> docker-compose -f /path/to/docker-compose.yml up -d
# stop: docker-compose -f /path/to/docker-compose.yml down

name: sapphire-orchestrator
services:

  luigid:
    #image: mabesa/sapphire-pipeline:latest
    build:
      context: ../
      dockerfile: ./apps/pipeline/Dockerfile
    ports:
      - "8082:8082"
    command: luigid

  config:
    image: mabesa/sapphire-configuration:latest
    build:
      context: ../
      dockerfile: ./apps/configuration_dashboard/dockerfile
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - ieasyhydroforecast_data_root_dir=${ieasyhydroforecast_data_root_dir}
      - SAPPHIRE_OPDEV_ENV=True
    command: ["R", "-e", "setwd('/app'); shiny::runApp('apps/configuration_dashboard/forecast_configuration.R', port = 3647, host = '0.0.0.0', launch.browser=FALSE)"]
    ports:
      - "80:3647"
    volumes:
      - ../../sensitive_data_forecast_tools/config:/sensitive_data_forecast_tools/config
      - ../../sensitive_data_forecast_tools/GIS:/sensitive_data_forecast_tools/GIS

  pentaddashboard:
    image: mabesa/sapphire-dashboard:latest
    build:
      context: ../
      dockerfile: ./apps/forecast_dashboard/Dockerfile
    working_dir: /app/apps/forecast_dashboard
    environment:
      - PYTHONPATH=/app
      - ieasyhydroforecast_data_root_dir=${ieasyhydroforecast_data_root_dir}
      - SAPPHIRE_OPDEV_ENV=True
      - IN_DOCKER_CONTAINER=True
    command: ["panel", "serve", "--allow-websocket-origin=34.202.229.208:5006", "pentad_dashboard.py", "--port=5006", "--address=0.0.0.0", "--show", "--autoreload"]
    ports:
      - "5006:5006"
    volumes:
      - ../../sensitive_data_forecast_tools/config:/sensitive_data_forecast_tools/config
      - ../../sensitive_data_forecast_tools/intermediate_data:/sensitive_data_forecast_tools/intermediate_data
      - ../../sensitive_data_forecast_tools/templates:/sensitive_data_forecast_tools/templates
      - ../../sensitive_data_forecast_tools/reports:/sensitive_data_forecast_tools/reports

  pipeline:
    depends_on:
      - luigid
    #image: mabesa/sapphire-pipeline:latest
    build:
      context: ../
      dockerfile: ./apps/pipeline/Dockerfile
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - ieasyhydroforecast_data_root_dir=${ieasyhydroforecast_data_root_dir}
    command: ['luigi', '--module', 'apps.pipeline.pipeline_docker']  # If run without luigid, '--local-scheduler']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socket
      - ../../sensitive_data_forecast_tools/config:/sensitive_data_forecast_tools/config
      - ../../sensitive_data_forecast_tools/daily_runoff:/sensitive_data_forecast_tools/daily_runoff
      - ../../sensitive_data_forecast_tools/intermediate_data:/sensitive_data_forecast_tools/intermediate_data




