"""add stats percentiles comparison to snow

Revision ID: 9f1e72108f01
Revises: a6210b339f17
Create Date: 2026-04-23 15:32:48.825337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1e72108f01'
down_revision: Union[str, Sequence[str], None] = 'a6210b339f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snow', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('snow', sa.Column('mean', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('std', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('min', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('max', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('q05', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('q25', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('q50', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('q75', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('q95', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('previous', sa.Float(), nullable=True))
    op.add_column('snow', sa.Column('current', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snow', 'current')
    op.drop_column('snow', 'previous')
    op.drop_column('snow', 'q95')
    op.drop_column('snow', 'q75')
    op.drop_column('snow', 'q50')
    op.drop_column('snow', 'q25')
    op.drop_column('snow', 'q05')
    op.drop_column('snow', 'max')
    op.drop_column('snow', 'min')
    op.drop_column('snow', 'std')
    op.drop_column('snow', 'mean')
    op.drop_column('snow', 'count')
    # ### end Alembic commands ###
