"""baseline

Revision ID: a6210b339f17
Revises: 
Create Date: 2026-04-23 14:15:57.107121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6210b339f17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydrographs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'SEASON', 'YEAR', name='horizontype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('horizon_in_year', sa.Integer(), nullable=False),
    sa.Column('day_of_year', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('q05', sa.Float(), nullable=True),
    sa.Column('q25', sa.Float(), nullable=True),
    sa.Column('q50', sa.Float(), nullable=True),
    sa.Column('q75', sa.Float(), nullable=True),
    sa.Column('q95', sa.Float(), nullable=True),
    sa.Column('norm', sa.Float(), nullable=True),
    sa.Column('previous', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'code', 'date', name='uq_hydrographs_horizon_code_date')
    )
    op.create_index('ix_hydrographs_horizon_code_date', 'hydrographs', ['horizon_type', 'code', 'date'], unique=False)
    op.create_index(op.f('ix_hydrographs_id'), 'hydrographs', ['id'], unique=False)
    op.create_table('meteo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meteo_type', sa.Enum('T', 'P', name='meteotype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('norm', sa.Float(), nullable=True),
    sa.Column('day_of_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meteo_type', 'code', 'date', name='uq_meteo_type_code_date')
    )
    op.create_index(op.f('ix_meteo_id'), 'meteo', ['id'], unique=False)
    op.create_index('ix_meteo_type_code_date', 'meteo', ['meteo_type', 'code', 'date'], unique=False)
    op.create_table('runoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'SEASON', 'YEAR', name='horizontype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('discharge', sa.Float(), nullable=True),
    sa.Column('predictor', sa.Float(), nullable=True),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('horizon_in_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'code', 'date', name='uq_runoffs_horizon_code_date')
    )
    op.create_index('ix_runoffs_horizon_code_date', 'runoffs', ['horizon_type', 'code', 'date'], unique=False)
    op.create_index(op.f('ix_runoffs_id'), 'runoffs', ['id'], unique=False)
    op.create_table('snow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snow_type', sa.Enum('HS', 'ROF', 'SWE', name='snowtype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('norm', sa.Float(), nullable=True),
    sa.Column('value1', sa.Float(), nullable=True),
    sa.Column('value2', sa.Float(), nullable=True),
    sa.Column('value3', sa.Float(), nullable=True),
    sa.Column('value4', sa.Float(), nullable=True),
    sa.Column('value5', sa.Float(), nullable=True),
    sa.Column('value6', sa.Float(), nullable=True),
    sa.Column('value7', sa.Float(), nullable=True),
    sa.Column('value8', sa.Float(), nullable=True),
    sa.Column('value9', sa.Float(), nullable=True),
    sa.Column('value10', sa.Float(), nullable=True),
    sa.Column('value11', sa.Float(), nullable=True),
    sa.Column('value12', sa.Float(), nullable=True),
    sa.Column('value13', sa.Float(), nullable=True),
    sa.Column('value14', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snow_type', 'code', 'date', name='uq_snow_type_code_date')
    )
    op.create_index(op.f('ix_snow_id'), 'snow', ['id'], unique=False)
    op.create_index('ix_snow_type_code_date', 'snow', ['snow_type', 'code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snow_type_code_date', table_name='snow')
    op.drop_index(op.f('ix_snow_id'), table_name='snow')
    op.drop_table('snow')
    op.drop_index(op.f('ix_runoffs_id'), table_name='runoffs')
    op.drop_index('ix_runoffs_horizon_code_date', table_name='runoffs')
    op.drop_table('runoffs')
    op.drop_index('ix_meteo_type_code_date', table_name='meteo')
    op.drop_index(op.f('ix_meteo_id'), table_name='meteo')
    op.drop_table('meteo')
    op.drop_index(op.f('ix_hydrographs_id'), table_name='hydrographs')
    op.drop_index('ix_hydrographs_horizon_code_date', table_name='hydrographs')
    op.drop_table('hydrographs')
    # ### end Alembic commands ###
