"""Tests for bin/initialize_meteo_history.sh (Phase P1b).

These tests exercise:
- the wrapper's --help and missing-env-file argument paths (subprocess-level);
- the embedded Python helper's HRU discovery + filter logic (unit-level,
  by importing the helper module from a synthetic file tree).

The helper module is generated by the wrapper at runtime as a Python script
written into the deployment log dir, then mounted into Docker. To test the
discovery + filter logic deterministically without Docker, we import the
helper-equivalent functions inline here (re-using the same regex contract
that the wrapper writes — see REANALYSIS_RE below). The integration of
those functions is exercised by running the embedded script via the
subprocess test path below using stdin redirection of the heredoc.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

# Repo root: apps/iEasyHydroForecast/tests/test_*.py -> parents[3]
_REPO_ROOT = Path(__file__).resolve().parents[3]
_WRAPPER = _REPO_ROOT / "bin" / "initialize_meteo_history.sh"
_METEO_FIXTURES = (
    _REPO_ROOT / "apps" / "iEasyHydroForecast" / "tests" / "fixtures" / "migration_csv" / "meteo"
)


# ---------------------------------------------------------------------------
# Test 1: --help returns 0 and prints usage.
# ---------------------------------------------------------------------------


def test_wrapper_help() -> None:
    """`bash initialize_meteo_history.sh --help` exits 0 and prints usage."""
    assert _WRAPPER.is_file(), f"wrapper missing: {_WRAPPER}"
    result = subprocess.run(
        ["bash", str(_WRAPPER), "--help"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"--help returned non-zero ({result.returncode}). "
        f"stdout={result.stdout!r}, stderr={result.stderr!r}"
    )
    out = result.stdout
    # Usage / option strings the operator will grep for.
    for needle in [
        "Usage:",
        "--dry-run",
        "--station-filter",
        "--meteo-type",
        "--api-url",
        "--batch-size",
    ]:
        assert needle in out, f"--help output missing: {needle!r}"


# ---------------------------------------------------------------------------
# Test 2: missing / non-existent env file is rejected with non-zero exit.
# ---------------------------------------------------------------------------


def test_wrapper_rejects_missing_env_file(tmp_path: Path) -> None:
    """A non-existent env file path must cause a non-zero exit."""
    nonexistent = tmp_path / "does_not_exist.env"
    assert not nonexistent.exists()
    result = subprocess.run(
        ["bash", str(_WRAPPER), str(nonexistent)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode != 0, (
        "wrapper accepted a missing env file path; expected non-zero exit. "
        f"stdout={result.stdout!r}, stderr={result.stderr!r}"
    )
    combined = (result.stdout + result.stderr).lower()
    assert "env file not found" in combined or "error" in combined


def test_wrapper_rejects_no_args() -> None:
    """Calling the wrapper with no args must exit non-zero with usage."""
    result = subprocess.run(
        ["bash", str(_WRAPPER)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode != 0
    combined = (result.stdout + result.stderr).lower()
    assert "env_file_path" in combined or "required" in combined


def test_wrapper_rejects_bad_meteo_type(tmp_path: Path) -> None:
    """--meteo-type accepts only T, P, or both."""
    fake_env = tmp_path / ".env_test"
    fake_env.write_text("")  # exists but is empty; --meteo-type is parsed first
    result = subprocess.run(
        ["bash", str(_WRAPPER), str(fake_env), "--meteo-type", "X"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode != 0
    combined = (result.stdout + result.stderr).lower()
    assert "must be" in combined or "meteo-type" in combined


# ---------------------------------------------------------------------------
# Embedded-helper discovery logic (unit-level).
#
# We test the discovery logic by re-implementing the regex + glob walk that
# the wrapper's embedded Python helper performs. This is a CONTRACT test:
# if the wrapper changes the filename pattern, this test must change in
# lockstep. Keep the regex literal identical to the one in the wrapper's
# heredoc (`REANALYSIS_RE`).
# ---------------------------------------------------------------------------


_REANALYSIS_RE = re.compile(r"^(?P<hru>[A-Za-z0-9]+)_(?P<mt>[TP])_reanalysis\.csv$")


def _discover(
    root: Path,
    station_filter: str = "",
    meteo_type_filter: str = "both",
) -> list[tuple[str, str, Path, Path | None]]:
    """Replica of the wrapper's discover_reanalysis_files() for unit testing."""
    out: list[tuple[str, str, Path, Path | None]] = []
    for path in sorted(root.glob("*_reanalysis.csv")):
        m = _REANALYSIS_RE.match(path.name)
        if m is None:
            continue
        hru = m.group("hru")
        mt = m.group("mt")
        if station_filter and hru != station_filter:
            continue
        if meteo_type_filter != "both" and mt != meteo_type_filter:
            continue
        dash_name = path.name.replace(".csv", "_dashboard.csv")
        dash_path = path.with_name(dash_name)
        out.append((hru, mt, path, dash_path if dash_path.is_file() else None))
    return out


def test_hru_discovery_unit() -> None:
    """Glob discovers both sentinel HRU codes 00001 and 00002 from fixtures."""
    found = _discover(_METEO_FIXTURES)
    # Expect: 00001 T, 00001 P, 00002 T, 00002 P  -> 4 files, 2 distinct HRUs.
    hrus = sorted({hru for hru, _mt, _r, _d in found})
    assert hrus == ["00001", "00002"], f"expected ['00001', '00002'], got {hrus}"

    types_seen = sorted({mt for _hru, mt, _r, _d in found})
    assert types_seen == ["P", "T"], f"expected ['P', 'T'], got {types_seen}"

    # Dashboard merge: 00001 T has a dashboard sibling; 00001 P / 00002 T / 00002 P
    # do not. Verify the dashboard-detection branch.
    dash_lookup = {(hru, mt): d for hru, mt, _r, d in found}
    assert dash_lookup[("00001", "T")] is not None, (
        "expected 00001 T dashboard sidecar to be detected"
    )
    assert dash_lookup[("00001", "P")] is None
    assert dash_lookup[("00002", "T")] is None
    assert dash_lookup[("00002", "P")] is None


def test_hru_discovery_station_filter() -> None:
    """--station-filter 00001 restricts discovery to HRU 00001 only."""
    found = _discover(_METEO_FIXTURES, station_filter="00001")
    hrus = sorted({hru for hru, _mt, _r, _d in found})
    assert hrus == ["00001"], f"station-filter leaked: {hrus}"
    # Both T and P for 00001 are still returned.
    types = sorted({mt for _hru, mt, _r, _d in found})
    assert types == ["P", "T"]


def test_meteo_type_filter_T_only() -> None:
    """--meteo-type T discovers only T-reanalysis CSVs."""
    found = _discover(_METEO_FIXTURES, meteo_type_filter="T")
    # 00001_T + 00002_T -> two files; no P.
    types = {mt for _hru, mt, _r, _d in found}
    assert types == {"T"}, f"meteo-type T leaked: {types}"
    hrus = sorted({hru for hru, _mt, _r, _d in found})
    assert hrus == ["00001", "00002"]


def test_meteo_type_filter_P_only() -> None:
    """--meteo-type P discovers only P-reanalysis CSVs."""
    found = _discover(_METEO_FIXTURES, meteo_type_filter="P")
    types = {mt for _hru, mt, _r, _d in found}
    assert types == {"P"}, f"meteo-type P leaked: {types}"


def test_meteo_type_and_station_filter_combined() -> None:
    """--station-filter 00001 + --meteo-type P leaves one file."""
    found = _discover(_METEO_FIXTURES, station_filter="00001", meteo_type_filter="P")
    assert len(found) == 1, f"expected exactly 1 match, got {len(found)}"
    hru, mt, _rpath, _dpath = found[0]
    assert hru == "00001"
    assert mt == "P"


# ---------------------------------------------------------------------------
# Sanity: the wrapper file embeds the same regex literal we test here.
# If the wrapper drifts, this test fails immediately — keeping the unit
# test honest about what code it represents.
# ---------------------------------------------------------------------------


def test_wrapper_embeds_expected_regex() -> None:
    """The wrapper's embedded helper must contain the REANALYSIS_RE we test."""
    text = _WRAPPER.read_text(encoding="utf-8")
    # The wrapper's regex literal is identical to _REANALYSIS_RE.pattern.
    needle = r'r"^(?P<hru>[A-Za-z0-9]+)_(?P<mt>[TP])_reanalysis\.csv$"'
    assert needle in text, (
        "wrapper no longer embeds the expected REANALYSIS_RE pattern; "
        "update tests in lockstep with the wrapper heredoc"
    )


# ---------------------------------------------------------------------------
# Sanity: --station-filter forward-contract is honored at the CLI surface.
# Validates the locked contract from P0 (and from this wrapper's CLI parse).
# ---------------------------------------------------------------------------


def test_wrapper_accepts_station_filter_flag(tmp_path: Path) -> None:
    """--station-filter is part of the locked forward contract from P0."""
    # We won't actually run a real migration here; we trip the env-file check
    # first by pointing at a missing file. The point is that the wrapper's
    # arg parser must NOT reject --station-filter as unknown.
    nonexistent = tmp_path / "does_not_exist.env"
    result = subprocess.run(
        [
            "bash",
            str(_WRAPPER),
            str(nonexistent),
            "--station-filter",
            "19999",
            "--dry-run",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    # We expect failure (env file missing), but stderr must NOT mention
    # --station-filter as unknown.
    combined = result.stdout + result.stderr
    assert "unknown argument" not in combined.lower() or ("--station-filter" not in combined), (
        "wrapper rejected --station-filter as unknown. Forward contract broken. "
        f"output: {combined!r}"
    )


# ---------------------------------------------------------------------------
# End-to-end: run the embedded Python helper directly in dry-run, against a
# tmp_path containing copies of the fixture CSVs. This exercises the
# generator + filter logic without the Docker layer.
# ---------------------------------------------------------------------------


def _extract_embedded_helper() -> str:
    """Extract the inlined Python helper from the wrapper's heredoc.

    The wrapper writes the helper via `cat > $PYTHON_HELPER <<'PYEOF' ... PYEOF`.
    There is exactly one such heredoc; we slice it out and return its contents.
    """
    text = _WRAPPER.read_text(encoding="utf-8")
    start = text.find("cat > \"$PYTHON_HELPER\" <<'PYEOF'\n")
    assert start != -1, "wrapper no longer contains the PYEOF heredoc"
    # Advance past the opening line.
    nl = text.find("\n", start)
    body_start = nl + 1
    body_end = text.find("\nPYEOF\n", body_start)
    assert body_end != -1, "wrapper PYEOF terminator not found"
    return text[body_start:body_end]


def test_embedded_helper_dry_run_inventory(tmp_path: Path) -> None:
    """End-to-end: run the embedded helper in dry-run; inventory mentions both HRUs."""
    # Copy fixtures into a tmp dir that mimics
    # <data_ref_dir>/intermediate_data/hindcast_forcing.
    meteo_dir = tmp_path / "hindcast_forcing"
    meteo_dir.mkdir(parents=True)
    for src in _METEO_FIXTURES.glob("*.csv"):
        (meteo_dir / src.name).write_text(src.read_text(encoding="utf-8"))

    # Materialise the helper.
    helper_text = _extract_embedded_helper()
    helper_path = tmp_path / "meteo_helper.py"
    helper_path.write_text(helper_text)

    env = os.environ.copy()
    env["METEO_DATA_DIR"] = str(meteo_dir)
    env["STATION_FILTER"] = ""
    env["METEO_TYPE_FILTER"] = "both"
    env["BATCH_SIZE"] = "500"
    env["API_URL"] = "http://127.0.0.1:1/meteo/"  # unreachable; dry-run never hits it
    env["CUTOFF_T"] = ""
    env["CUTOFF_P"] = ""

    result = subprocess.run(
        [sys.executable, str(helper_path), "--dry-run"],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    assert result.returncode == 0, (
        f"helper dry-run failed: stdout={result.stdout!r}, stderr={result.stderr!r}"
    )
    out = result.stdout
    # Both HRU codes appear in the inventory listing.
    assert "hru=00001" in out, f"00001 missing from inventory: {out}"
    assert "hru=00002" in out, f"00002 missing from inventory: {out}"
    # Both meteo types appear.
    assert "meteo_type=T" in out and "meteo_type=P" in out
    # Distinct HRU count summary line.
    assert "distinct HRUs discovered (redacted count): 2" in out
    # Dashboard merge detected on the 00001 T pair.
    assert "dashboard=yes" in out
    # DRY_RUN guarantees no POST.
    assert "would POST" in out


def test_embedded_helper_station_filter(tmp_path: Path) -> None:
    """End-to-end: --station-filter restricts the inventory to one HRU."""
    meteo_dir = tmp_path / "hindcast_forcing"
    meteo_dir.mkdir(parents=True)
    for src in _METEO_FIXTURES.glob("*.csv"):
        (meteo_dir / src.name).write_text(src.read_text(encoding="utf-8"))

    helper_path = tmp_path / "meteo_helper.py"
    helper_path.write_text(_extract_embedded_helper())

    env = os.environ.copy()
    env["METEO_DATA_DIR"] = str(meteo_dir)
    env["STATION_FILTER"] = "00001"
    env["METEO_TYPE_FILTER"] = "both"
    env["BATCH_SIZE"] = "500"
    env["API_URL"] = "http://127.0.0.1:1/meteo/"
    env["CUTOFF_T"] = ""
    env["CUTOFF_P"] = ""

    result = subprocess.run(
        [sys.executable, str(helper_path), "--dry-run"],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    assert result.returncode == 0, f"helper failed: {result.stderr!r}"
    out = result.stdout
    assert "hru=00001" in out
    assert "hru=00002" not in out, "station-filter leaked 00002"
    assert "distinct HRUs discovered (redacted count): 1" in out


def test_embedded_helper_meteo_type_T_only(tmp_path: Path) -> None:
    """End-to-end: --meteo-type T omits all P entries from the inventory."""
    meteo_dir = tmp_path / "hindcast_forcing"
    meteo_dir.mkdir(parents=True)
    for src in _METEO_FIXTURES.glob("*.csv"):
        (meteo_dir / src.name).write_text(src.read_text(encoding="utf-8"))

    helper_path = tmp_path / "meteo_helper.py"
    helper_path.write_text(_extract_embedded_helper())

    env = os.environ.copy()
    env["METEO_DATA_DIR"] = str(meteo_dir)
    env["STATION_FILTER"] = ""
    env["METEO_TYPE_FILTER"] = "T"
    env["BATCH_SIZE"] = "500"
    env["API_URL"] = "http://127.0.0.1:1/meteo/"
    env["CUTOFF_T"] = ""
    env["CUTOFF_P"] = ""

    result = subprocess.run(
        [sys.executable, str(helper_path), "--dry-run"],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    assert result.returncode == 0
    out = result.stdout
    # The dotted scan must show ONLY meteo_type=T lines, never meteo_type=P.
    inventory_lines = [
        line for line in out.splitlines() if "meteo_type=" in line and "hru=" in line
    ]
    assert inventory_lines, f"no inventory lines emitted: {out}"
    for line in inventory_lines:
        assert "meteo_type=T" in line, f"P leaked into T-only inventory line: {line!r}"


def test_embedded_helper_no_files_exits_cleanly(tmp_path: Path) -> None:
    """An empty discovery (no matching files) exits 0 with a clear message."""
    empty_dir = tmp_path / "hindcast_forcing"
    empty_dir.mkdir(parents=True)

    helper_path = tmp_path / "meteo_helper.py"
    helper_path.write_text(_extract_embedded_helper())

    env = os.environ.copy()
    env["METEO_DATA_DIR"] = str(empty_dir)
    env["STATION_FILTER"] = ""
    env["METEO_TYPE_FILTER"] = "both"
    env["BATCH_SIZE"] = "500"
    env["API_URL"] = "http://127.0.0.1:1/meteo/"
    env["CUTOFF_T"] = ""
    env["CUTOFF_P"] = ""

    result = subprocess.run(
        [sys.executable, str(helper_path), "--dry-run"],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    assert result.returncode == 0
    assert "No reanalysis CSVs discovered" in result.stdout


# ---------------------------------------------------------------------------
# Quick syntax sanity: the embedded helper compiles.
# Catches accidental shell-variable leaks into the heredoc.
# ---------------------------------------------------------------------------


def test_embedded_helper_compiles() -> None:
    """The embedded Python helper must be syntactically valid Python."""
    src = _extract_embedded_helper()
    try:
        compile(src, "embedded_meteo_helper", "exec")
    except SyntaxError as exc:  # pragma: no cover - failure path
        pytest.fail(f"embedded helper has syntax errors: {exc}")
