"""baseline

Revision ID: 34b227f37299
Revises: 
Create Date: 2026-04-24 13:58:07.416500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b227f37299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'QUARTER', 'SEASON', name='horizontype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('model_type', sa.Enum('TSMIXER', 'TIDE', 'TFT', 'ENSEMBLE_MEAN', 'NEURAL_ENSEMBLE', 'RRAM', 'LINEAR_REGRESSION', 'GBT', 'LR_BASE', 'LR_SM', 'LR_SM_DT', 'LR_SM_ROF', 'MC_ALD', 'SM_GBT', 'SM_GBT_LR', 'SM_GBT_NORM', 'SKILLED_MEAN', 'NAIVE_MEAN', name='modeltype'), nullable=False),
    sa.Column('basin_name', sa.String(length=100), nullable=True),
    sa.Column('station_label', sa.String(length=100), nullable=True),
    sa.Column('forecasted_discharge', sa.Float(), nullable=True),
    sa.Column('fc_lower', sa.Float(), nullable=True),
    sa.Column('fc_upper', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('sdivsigma', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'year', 'horizon_value', 'code', name='uq_bulletins_horizon_year_number_code')
    )
    op.create_index('ix_bulletins_horizon_year_number', 'bulletins', ['horizon_type', 'year', 'horizon_value'], unique=False)
    op.create_index(op.f('ix_bulletins_id'), 'bulletins', ['id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'QUARTER', 'SEASON', name='horizontype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('model_type', sa.Enum('TSMIXER', 'TIDE', 'TFT', 'ENSEMBLE_MEAN', 'NEURAL_ENSEMBLE', 'RRAM', 'LINEAR_REGRESSION', 'GBT', 'LR_BASE', 'LR_SM', 'LR_SM_DT', 'LR_SM_ROF', 'MC_ALD', 'SM_GBT', 'SM_GBT_LR', 'SM_GBT_NORM', 'SKILLED_MEAN', 'NAIVE_MEAN', name='modeltype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('target', sa.Date(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('horizon_in_year', sa.Integer(), nullable=False),
    sa.Column('composition', sa.String(length=100), nullable=True),
    sa.Column('q05', sa.Float(), nullable=True),
    sa.Column('q25', sa.Float(), nullable=True),
    sa.Column('q75', sa.Float(), nullable=True),
    sa.Column('q95', sa.Float(), nullable=True),
    sa.Column('forecasted_discharge', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'code', 'model_type', 'date', 'target', name='uq_forecasts_horizon_code_model_date_target')
    )
    op.create_index('ix_forecasts_horizon_code_date_target', 'forecasts', ['horizon_type', 'code', 'date', 'target'], unique=False)
    op.create_index('ix_forecasts_horizon_code_model_date_target', 'forecasts', ['horizon_type', 'code', 'model_type', 'date', 'target'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_table('long_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'QUARTER', 'SEASON', name='horizontype'), nullable=False),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model_type', sa.Enum('TSMIXER', 'TIDE', 'TFT', 'ENSEMBLE_MEAN', 'NEURAL_ENSEMBLE', 'RRAM', 'LINEAR_REGRESSION', 'GBT', 'LR_BASE', 'LR_SM', 'LR_SM_DT', 'LR_SM_ROF', 'MC_ALD', 'SM_GBT', 'SM_GBT_LR', 'SM_GBT_NORM', 'SKILLED_MEAN', 'NAIVE_MEAN', name='modeltype'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('composition', sa.String(length=100), nullable=True),
    sa.Column('q', sa.Float(), nullable=True),
    sa.Column('q_obs', sa.Float(), nullable=True),
    sa.Column('q_xgb', sa.Float(), nullable=True),
    sa.Column('q_lgbm', sa.Float(), nullable=True),
    sa.Column('q_catboost', sa.Float(), nullable=True),
    sa.Column('q_loc', sa.Float(), nullable=True),
    sa.Column('q05', sa.Float(), nullable=True),
    sa.Column('q10', sa.Float(), nullable=True),
    sa.Column('q25', sa.Float(), nullable=True),
    sa.Column('q50', sa.Float(), nullable=True),
    sa.Column('q75', sa.Float(), nullable=True),
    sa.Column('q90', sa.Float(), nullable=True),
    sa.Column('q95', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'horizon_value', 'code', 'date', 'model_type', 'valid_from', 'valid_to', name='uq_long_forecasts_horizon_type_value_code_date_model_from_to')
    )
    op.create_index('ix_long_forecasts_horizon_type_value_code_date_model_from_to', 'long_forecasts', ['horizon_type', 'horizon_value', 'code', 'date', 'model_type', 'valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('ix_long_forecasts_id'), 'long_forecasts', ['id'], unique=False)
    op.create_table('lr_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'QUARTER', 'SEASON', name='horizontype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('horizon_in_year', sa.Integer(), nullable=False),
    sa.Column('discharge_avg', sa.Float(), nullable=True),
    sa.Column('predictor', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('intercept', sa.Float(), nullable=True),
    sa.Column('forecasted_discharge', sa.Float(), nullable=True),
    sa.Column('q_mean', sa.Float(), nullable=True),
    sa.Column('q_std_sigma', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('rsquared', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'code', 'date', name='uq_lr_forecasts_horizon_code_date')
    )
    op.create_index('ix_lr_forecasts_horizon_code_date', 'lr_forecasts', ['horizon_type', 'code', 'date'], unique=False)
    op.create_index(op.f('ix_lr_forecasts_id'), 'lr_forecasts', ['id'], unique=False)
    op.create_table('lr_visibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'QUARTER', 'SEASON', name='horizontype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('horizon_value', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'code', 'month', 'horizon_value', 'year', name='uq_lr_visibility_horizon_code_month_number_year')
    )
    op.create_index('ix_lr_visibility_horizon_code_month_number', 'lr_visibility', ['horizon_type', 'code', 'month', 'horizon_value'], unique=False)
    op.create_index(op.f('ix_lr_visibility_id'), 'lr_visibility', ['id'], unique=False)
    op.create_table('skill_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horizon_type', sa.Enum('DAY', 'PENTAD', 'DECADE', 'MONTH', 'QUARTER', 'SEASON', name='horizontype'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('model_type', sa.Enum('TSMIXER', 'TIDE', 'TFT', 'ENSEMBLE_MEAN', 'NEURAL_ENSEMBLE', 'RRAM', 'LINEAR_REGRESSION', 'GBT', 'LR_BASE', 'LR_SM', 'LR_SM_DT', 'LR_SM_ROF', 'MC_ALD', 'SM_GBT', 'SM_GBT_LR', 'SM_GBT_NORM', 'SKILLED_MEAN', 'NAIVE_MEAN', name='modeltype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('horizon_in_year', sa.Integer(), nullable=False),
    sa.Column('composition', sa.String(length=100), nullable=True),
    sa.Column('sdivsigma', sa.Float(), nullable=True),
    sa.Column('nse', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('n_pairs', sa.Integer(), nullable=True),
    sa.Column('crps', sa.Float(), nullable=True),
    sa.Column('pbias', sa.Float(), nullable=True),
    sa.Column('kgelf', sa.Float(), nullable=True),
    sa.Column('nse_log', sa.Float(), nullable=True),
    sa.Column('fhv', sa.Float(), nullable=True),
    sa.Column('flv', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizon_type', 'code', 'model_type', 'date', 'horizon_in_year', name='uq_skill_metrics_horizon_code_model_date_horizon')
    )
    op.create_index('ix_skill_metrics_horizon_code_model_date', 'skill_metrics', ['horizon_type', 'code', 'model_type', 'date'], unique=False)
    op.create_index(op.f('ix_skill_metrics_id'), 'skill_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_metrics_id'), table_name='skill_metrics')
    op.drop_index('ix_skill_metrics_horizon_code_model_date', table_name='skill_metrics')
    op.drop_table('skill_metrics')
    op.drop_index(op.f('ix_lr_visibility_id'), table_name='lr_visibility')
    op.drop_index('ix_lr_visibility_horizon_code_month_number', table_name='lr_visibility')
    op.drop_table('lr_visibility')
    op.drop_index(op.f('ix_lr_forecasts_id'), table_name='lr_forecasts')
    op.drop_index('ix_lr_forecasts_horizon_code_date', table_name='lr_forecasts')
    op.drop_table('lr_forecasts')
    op.drop_index(op.f('ix_long_forecasts_id'), table_name='long_forecasts')
    op.drop_index('ix_long_forecasts_horizon_type_value_code_date_model_from_to', table_name='long_forecasts')
    op.drop_table('long_forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index('ix_forecasts_horizon_code_model_date_target', table_name='forecasts')
    op.drop_index('ix_forecasts_horizon_code_date_target', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_bulletins_id'), table_name='bulletins')
    op.drop_index('ix_bulletins_horizon_year_number', table_name='bulletins')
    op.drop_table('bulletins')
    # ### end Alembic commands ###
