name: Test & deploy forecast configuration

env:
    IMAGE_NAME: mabesa/sapphire-configuration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_Dckerhub:
    runs-on: ubuntu-latest
    name: A job to push the Docker image to Dockerhub

    steps:
    # To use this repository's private action, you must check out the
    # repository.
    - name: Checkout
      uses: actions/checkout@v4

    # Rename the image
    - name: Rename the image
      run: |
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    # Run the dockerization & deployment script
    - name: Build Docker image
      run: |
        #docker build --no-cache -t linreg_test -f .apps/forecast_linreg/Dockerfile .
        docker build --no-cache -t station_dashboard -f ./apps/configuration_dashboard/dockerfile .

    # Log in to the Docker registry
    - name: Log in to the Docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push the image to Dockerhub
    - name: Push the image to Dockerhub
      run: |
        docker push "$IMAGE_NAME:$IMAGE_TAG"



