name: Dockerize say_hello_script

on: [push]

jobs: 
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps: 
            # To use this repository's private action, you must check out the 
            # repository.
            - name: Checkout
              uses: actions/checkout@v4

            # Set script permissions
            - name: Set script permissions
              run: |
                chmod +x ./iEasyHydroForecast/test_deploy.sh

            # Build Docker image
            - name: Build Docker image
              run: |
                docker build -t say_hello ./iEasyHydroForecast

            # Run the Docker image
            - name: Run Docker image
              run: |
                docker run say_hello Moon