name: Dockerize say_hello_script

on: [push]

jobs: 
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps: 
            # To use this repository's private action, you must check out the 
            # repository.
            - name: Checkout
              uses: actions/checkout@v4
            # 
            - name: Build Docker image
              run: |
                docker build -t say_hello ./iEasyHydroForecast

            # Use the output from the `hello` step
            - name: Run Docker image
              run: |
                docker run say_hello 