name: Test-deploy backend

env:
    IMAGE_NAME: mabesa/sapphire-backend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_test_ieasyhydroforecast:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set PYTHONPATH
      run: |
        # Adding the iEasyHydroForecast folder to the PYTHONPATH
        echo "PYTHONPATH=${GITHUB_WORKSPACE}/apps/iEasyHydroForecast" >> $GITHUB_ENV
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        if [ -f python_requirements.txt ]; then pip install -r python_requirements.txt; fi
        pip install git+https://github.com/hydrosolutions/ieasyhydro-python-sdk
        pip install -e ./apps/iEasyHydroForecast
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      working-directory: ./apps
      run: |
        python -m unittest discover -s iEasyHydroForecast/tests -p 'test_*.py'

  lint_and_test_backend:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set PYTHONPATH
      run: |
        # Adding the iEasyHydroForecast folder to the PYTHONPATH
        echo "PYTHONPATH=${GITHUB_WORKSPACE}/apps/iEasyHydroForecast" >> $GITHUB_ENV
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        #if [ -f pyton_requirements.txt ]; then pip install -r pyton_requirements.txt; fi
        python -m pip install -r ./apps/backend/requirements.txt
        pip install git+https://github.com/hydrosolutions/ieasyhydro-python-sdk
        pip install git+https://github.com/hydrosolutions/ieasyhydro-python-sdk
        pip install -e ./apps/iEasyHydroForecast
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ./apps
      run: |
        SAPPHIRE_TEST_ENV=True python -m pytest

  push_to_Dckerhub:
    needs: [lint_and_test_ieasyhydroforecast, lint_and_test_backend]
    runs-on: ubuntu-latest
    name: A job to push the Docker image to Dockerhub

    steps:
    # To use this repository's private action, you must check out the
    # repository.
    - name: Checkout
      uses: actions/checkout@v4

    # Rename the image
    - name: Rename the image
      run: |
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    # Run the dockerization & deployment script
    - name: Build Docker image
      run: |
        docker build --no-cache -t "$IMAGE_NAME:$IMAGE_TAG" -f ./apps/backend/Dockerfile .

    # Log in to the Docker registry
    - name: Log in to the Docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push the image to Dockerhub
    - name: Push the image to Dockerhub
      run: |
        docker push "$IMAGE_NAME:$IMAGE_TAG"



